### ISSUE TITLE
Factory preset issues with VST2 and VST3

### ISSUE THREAD

**Issue by earlevel** [iPlug2/iPlug2#317]
Offered as a simple-to-reproduce example showing problems with factory presets with VST2 and VST3, primarily for the purpose of discussing wider problems with VST2 and VST3.

Repro—add factory presets to IPlugEffect:

In IPlugEffect.h, change the number of presets to 10

`const int kNumPrograms = 10;`

In common-mac.xcconfig, append VST3_PRESET_LIST to VST3_DEFS (aside: can't we be more elegant here, perhaps inferring this from kNumPrograms?):

`VST3_DEFS = VST3_API $PLUGIN_DEFS IPLUG_EDITOR=1 IPLUG_DSP=1 VST3_PRESET_LIST`

In IPlugEffect.cpp, create some presets by inserting this in the constructor:

```
  // makes some factory presets
  for (int idx = 0; idx < kNumPrograms; idx++) {
    std::string s = "Preset " + std::to_string(idx);
    MakePreset(s.c_str(), (double)idx);
  }
```
Build VST2 and VST3, and build AU for a comparison with one that works right.

Open an new project in Reaper, and add all three type of IPlugEffect to a track. Start with the AU. Click the Presets list, and verify it shows Preset 0 through Preset 9, and note that selecting that the number also indicates the gain of the preset (Preset 9 give a gain control value of 9).

Now try it with VST3. The preset are there, and work as expected until you get to the higher numbers—Preset 9 has a gain of 8 (because it's really preset 8 being recalled, when you select 9). This is not a bug in Reaper, even though this make work right in some hosts, it's a behavior of Reaper that illustrates underlying implementation problems with VST3 in IPlug1/2. I've fixed this in IPlug1, but the changes are a combination of individual bug fixes and architectural implementation, so I can't easily issue a pull request and have any hope that someone would implement it or take time to figure out what it does, without further discussion.

Now VST2. The preset menu works as expected, but preset behavior differs from AU and VST3: Bring up Preset 9, and change the gain knob to read 47%. Choose Preset 8, and change the gain to 23. Go back to Preset 9—it's 47%. And Preset 8 is 23%. VST2 overwrite presets in memory with the current parameter value when you change presets. AU and VST3 don't do this. While an argument could be made this is a "feature", the fact that the settings are forgotten when the plugin closes make it hard to justify. The case is ModifyCurrentPreset, used liberally in IPlugVST.cpp for unclear reasons. (Even effSetProgramName changes the preset's param values, in addition to the name—hard to justify that.)

**Comment by AlexHarker** [comment]
Thanks Nigel. This is all very helpful.

I've fixed the VST3 preset number issue in c7298f69768f304d2bc4439b20a30f2fc3c3872e directly on master. I don't see that it needs anything other than a round, but if you are able to double check that would be appreciated.

This had been done somewhat similarly in my fork of IPlug1 here (https://github.com/AlexHarker/wdl-ol/blob/master/WDL/IPlug/IPlugVST3.cpp#L409) but when I migrated all my changes to iPlug2 manually this somehow got lost, or possibly I never completed the spreadsheet I made (which I'll make sure to return to).

the VST2 preset stuff will need a bit more time, but I'm sure @olilarkin or I will look at it, so I'll leave the issue open. Presets (as distinct from state more generally) are certainly something that could be improved in iplug in my opinion and for my own releases I have tended to use internal preset management and turned off the generic preset handling - they also mean different things in vst2/vst3/au and function quite differently which poses a challenge for having them do sensible things all the time.

**Comment by earlevel** [comment]
Thanks, Alex.

OK, I see a lot of changes in IPlug2, including normalizedParamToPlain, which Reaper uses (and was missing in wdl/ol). Basically, my fix in IPlug1 was to add that, fix rounding as you did, and fix the stepCount in the initialization. That last one is still wrong in IPlug2. The issue is that the line

`parameters.addParameter(new IPlugVST3PresetParameter(pPlug->NPresets()));`

should use `pPlug->NPresets() - 1`, because the value is a stepCount, which is defined by Steinberg as the number of steps not including the base value. It will probably work anyway in most hosts without fixing it, but it's out of spec and I don't know if it will cause a problem for some host somewhere. Reaper, for instance, uses normalizedParamToPlain/plainParamToNormalized to resolve the settings, so it doesn't matter. However, it should cause no problems to fix it. I fixed it that way in IPlug1, and it worked for all hosts tested.

(Yes, I'm not a fan of using this built-in stuff either, but had to for my plugins because they were recreations of my legacy TDM plugins, and it was decided that the GUI would not change.)

**Comment by AlexHarker** [comment]
Yes - I'd noticed the step count issue last night (not the best name given that it is not actually a count, but I saw your forum posts about this and checked the docs to confirm that's how it is supposed to be used). I've just pushed a fix now (47876fda2eaa9b1578d0fa0aaa2d0209453dc7b6). That fixes the step within the parameter, rather than on the line you specify which I think is conceptually a bit nicer. If you could check it on cubase that would be great.

As you say, VST3 in iplug2 is substantially refactored and changed. However, when I search I don't see a custom implementation of normalizedParamToPlain in our code - perhaps I am missing something, or do you mean toPlain/toNormalised inIPlugVST3_Parameter.h?

**Comment by earlevel** [comment]
OK, it's coming back to me (and this is what i meant by "whack-a-mole"):

OK, your fix:

'pPlug->RestorePreset(std::round(pPlug->NPresets() * value));'

certainly should be

'pPlug->RestorePreset(std::round((pPlug->NPresets() - 1) * value));'

Right? Otherwise, if you have ten presets, 0-9, a value of 1 would yield 10. So why does it seem to work?  The "compensating errors" I mentioned. The fix works for Reaper and Cubase, but there's a high likelihood of it failing on another host—the math is wrong so it depends on the host making the right assumption to allow complementary errors.

In addition to the fix above, the stepCount fix I mentioned before needs to be in IPlugVST3_ControllerBase.h:

`parameters.addParameter(new IPlugVST3PresetParameter(pPlug->NPresets() - 1));`

At that point, it'll work again in Cubase, and probably most others, but break Reaper. That's because Reaper does an unusual step of asking the plugin what preset is selected, after Reaper requests the preset change (to allow plugins to renumber their own preset, supposedly). To do that, Reaper needs to plainParamToNormalized and NormalizedParamToPlain to be implemented. If not—that is, if the plugin simply returns the input values, which is the default implementation—Reaper does its own calculation. Unfortunately, Reaper has a bug in its calculation, so it will be wrong. IIRC, it's pretty similar to the mistake of the stepCount being wrong—in any case its an off-by-one error. Cockos acknowledged the goof, but correctly said that if the plugin gives the right responses (which I figured out is via the two calls mentioned her), it will work anyway.

I just tested the total fix, works, I do a pull request if I have time...

**Comment by earlevel** [comment]
OK, I hit Comment, and ding the email notice of your reply...

Yes, I did look at ToPlain/ToNormalized, it similarly didn't have the necessary implementation, and it looked seductive. But no, Reaper never hits those on preset changes, breakpoints not touched. It for sure calls plainParamToNormalized/normalizedParamToPlain though, and that fixes it. So, basically something like this (or use them to call your ToPlain/ToNormalized, since you've got them and it seems like the right thing to do):

```
ParamValue PLUGIN_API IPlugVST3::normalizedParamToPlain(ParamID tag, ParamValue valueNormalized)
{
  if (tag == kPresetParam)
    return std::round((NPresets() - 1) * valueNormalized);

  return EditController::normalizedParamToPlain(tag, valueNormalized);
}

ParamValue PLUGIN_API IPlugVST3::plainParamToNormalized (ParamID tag, ParamValue plainValue)
{
  if (tag == kPresetParam)
    return plainValue / (NPresets() - 1);

  return EditController::plainParamToNormalized(tag, plainValue);
}
```

**Comment by earlevel** [comment]
And yes, "stepCount" is really annoying in VST. I get it, a toggle switch has a stepCount of 1 because it can only be moved a single step, but...

**Comment by AlexHarker** [comment]
In the old version my fix was not with the minus one because that wasn't how I was reporting the parameter. Now it is so I've changed that.

The default implementation for plainParamToNormalized calls the parameter versions (toPlain/toNormalised) so I prefer to provide this at the parameter level rather than customising where we don't need it. I've now provided those for the preset parameter correctly and it works in reaper, so it would just be good to test in another host.

**Comment by earlevel** [comment]
Yes, I checked it in Reaper and Cubase 9. It's the right fix and I'm confident that it will work in any host that's not outright broken.

As far as test, I really don't have a lot of hosts I can think of that support VST3 factory/baked-in presets. Studio One oddly supports it for VST but not VST3, Digital Performer doesn't support them for anything, etc. While the support outlook is probably better in Windows, I don't have a lot of hosts there in my VM. (Personally, I'm just ticking the box on this kind of preset support—I just don't want it to work wrong. Availability is not a concern.)

Thanks again, Alex.

**Comment by olilarkin** [comment]
I have reworked VST3_PRESET_LIST here https://github.com/iPlug2/iPlug2/commit/6e0266cfe0e6f9ef3cc00695faa3bd23bd5e5666

May also make it so that you don't specify VST3_PRESET_LIST and instead just set kNumPrograms = 0 for VST3 if you don't want it. 

Only Reaper seems to show VST3 "Program Lists" I cannot see the factory presets, even in Cubase
