### ISSUE TITLE
support for creating/copying plugins outside the iPlug2 SDK tree

### ISSUE THREAD

**Issue by jjYBdx4IL** [iPlug2/iPlug2#458]
Currently, the IPLUG2_ROOT setting in the SDK root's common-win.props overwrites the plugin project's own setting and makes the build fail. Is there any way to avoid this?

I want to put my plugin source code into my source code repo without adding the entire SDK.

**Comment by olilarkin** [comment]
is this what you want? https://github.com/iPlug2/iPlug2OutOfSourceExample

**Comment by jjYBdx4IL** [comment]
Essentially yes. I was just hoping that there is a nicer solution that simply does not overwrite already existing variables.

**Comment by olilarkin** [comment]
hmm i am not sure IPLUG2_ROOT should be in common-win.props at all, will investigate

**Comment by AlexHarker** [comment]
It is in the common xcconfig - it totally makes sense that it is *used* but not defined in these common files.

**Comment by AlexHarker** [comment]
It is defined in common-win.props, but I presume that if you define it at a higher level (project level or a project specific props file) then it will use that one - this seems like a perfectly sensible solution to me (in fact it saves defining it when you are in a normal location).

BTW - @jjYBdx4IL - if you just want a separate repo you can put your plugin in Projects/MyPlugin - the Projects/ folder is .gitignored and then you can set up your own repo in your plugin folder - there is no need to be in a totally new location if you don't want to be.

**Comment by sstillwell** [comment]
> BTW - @jjYBdx4IL - if you just want a separate repo you can put your plugin in Projects/MyPlugin - the Projects/ folder is .gitignored and then you can set up your own repo in your plugin folder - there is no need to be in a totally new location if you don't want to be.

The only issue with that is that your plugin's repository will not track which commit of IPlug2 it's meant to work with, so you can't accurately reproduce the state by tagging or branching and then later checking that commit out.

...or am I missing something?

**Comment by jjYBdx4IL** [comment]
Is there any format specification/documentation/schema definition for common-win.props files? Maybe there is an if-element to check if IPLUG2_ROOT is empty.

**Comment by jjYBdx4IL** [comment]
Fixed.
https://docs.microsoft.com/en-us/cpp/build/reference/vcxproj-file-structure?view=vs-2019

**Comment by baktery** [comment]
I also have an independent repository with my sources outside the iPlug2 SDK tree. Previously as a temporal workaround I changed locally the iPlug2 repository .props file. Today I decided to do it in a proper way and I found this thread talking about it.

@olilarkin you have the iPlug2OutOfSourceExample sample but there you have to overwrite already existing variables.

I see that with @jjYBdx4IL fix https://github.com/jjYBdx4IL/iPlug2/commit/5336b123386d156a3b75248f8fbd30375c472f7b (not overwriting IPLUG2_ROOT if already exist) I don't have to change anything, everything works automatically without extra changes: the duplicate.py script already created the proper prop file and combined with @jjYBdx4IL fix nothing extra has to be done, both things together resolve the issue.

Do not overwriting IPLUG2_ROOT seems a clean way to support outside iPlug2 SDK tree projects.

The problem is that @jjYBdx4IL fix is only available in his own iPlug2 branch repository.

Will the change be included in the official iPlug2 repository? Or will it be resolved with a different approach?

**Comment by olilarkin** [comment]
probably, havent had time to look at it

**Comment by olilarkin** [comment]
Is this not solved, by just removing IPLUG2_ROOT from common-win.props

I don't think it should be there

https://github.com/iPlug2/iPlug2/commit/010c39c3b2215b62e2199ea14f9cab5f5ffec87f

**Comment by baktery** [comment]
I think so, it sounds good. I'll try it later on my side.

**Comment by baktery** [comment]
Tested on windows, it works fantastically well, thanks!

**Comment by olilarkin** [comment]
does this also address your issue @jjYBdx4IL ?

**Comment by jjYBdx4IL** [comment]
Yes. TY!
