### ISSUE TITLE
Fix skia prebuilt libs warnings

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#791]
ld: warning: object file (../../iPlug2/Dependencies/Build/mac/lib/libskunicode.a(libicu.icudtl_dat.o)) was built for newer macOS version (10.15) than being linked (10.13)

on M1

ld: warning: object file (../../iPlug2/Dependencies/Build/mac/lib/libskunicode.a(libicu.icudtl_dat.o)) was built for newer macOS version (11.0) than being linked (10.13)

**Comment by AlexHarker** [comment]
I suspect these warnings will actually represent a minimum Mac OS for the plugin to run.

What are the OS requirements fo skin in the version we are currently using, and is this simply a case of redoing our script config for the skit build, or is it more complex?

**Comment by olilarkin** [comment]
I think this is fixed after updating to skia/chromem97. I don't see the warning anymore

**Comment by AlexHarker** [comment]
Have you uploaded new pre-built libs?

**Comment by olilarkin** [comment]
yes

**Comment by AlexHarker** [comment]
I still get warnings linking on intel:

ld: warning: object file (../../../Dependencies/Build/mac/lib/libskunicode.a(libicu.icudtl_dat.o)) was built for newer macOS version (11.0) than being linked (10.11)

That's a newer OS version than before on intel, so I can tell the build has changed, but it's not fixed it unfortunately

**Comment by olilarkin** [comment]
Damn

**Comment by AlexHarker** [comment]
Yeah - I'm happy to take a shot at it...

**Comment by olilarkin** [comment]
I expect we need to patch the skunicode gn file with macOS-min setting

**Comment by AlexHarker** [comment]
Yep - it looks like it is probably just using the OS it is built on at the mo

**Comment by AlexHarker** [comment]
The problem isn't actually with skunicode itself - the issue is with an external dependency (icu) - this appears to build a data file into an object that doesn't get the right build settings. I don't really understand how the build system works so I can't yet figure out how to fix it.
